export const GET_SPORT_ARTICLES_START = "GET_SPORT_ARTICLES_START";
export const SET_SPORT_ARTICLES_START = "SET_SPORT_ARTICLES_START";
export const SET_SPORT_ARTICLES_FAILED = "SET_SPORT_ARTICLES_FAILED";

export const GET_FASHION_ARTICLES_START = "GET_FASHION_ARTICLES_START";
export const SET_FASHION_ARTICLES_START = "SET_FASHION_ARTICLES_START";
